# Generated by Django 5.1.3 on 2024-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.PositiveSmallIntegerField()),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('grade_c', models.PositiveSmallIntegerField()),
                ('grade_b', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
    ]
