# Generated by Django 5.1.3 on 2024-12-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
