# Generated by Django 5.1.3 on 2025-02-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0003_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150)),
            ],
        ),
    ]
