# Generated by Django 5.1.3 on 2025-02-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0004_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
