# Generated by Django 5.1.3 on 2025-07-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0008_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
